services:
  nginx:
    image: nginx:1.27-alpine
    container_name: rinha-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"

  api1:
    image: mxlange/rinha-go-2026:v0.0.6
    container_name: rinha-api1
    environment:
      PORT: "8080"
      RESOURCES_DIR: /app/resources
      SEARCH_BACKEND: "exact"
      HNSW_M: "16"
      HNSW_EF_SEARCH: "2"
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150MB"

  api2:
    image: mxlange/rinha-go-2026:v0.0.6
    container_name: rinha-api2
    environment:
      PORT: "8080"
      RESOURCES_DIR: /app/resources
      SEARCH_BACKEND: "exact"
      HNSW_M: "16"
      HNSW_EF_SEARCH: "2"
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150MB"

networks:
  rinha-net:
    driver: bridge
