@baseUrl = http://localhost:9999

### Health
GET {{baseUrl}}/ready

### Score 0.0
POST {{baseUrl}}/fraud-score
Content-Type: application/json

{
  "id": "tx-1329056812",
  "transaction": {
    "amount": 41.12,
    "installments": 2,
    "requested_at": "2026-03-11T18:45:53Z"
  },
  "customer": {
    "avg_amount": 82.24,
    "tx_count_24h": 3,
    "known_merchants": ["MERC-003", "MERC-016"]
  },
  "merchant": {
    "id": "MERC-016",
    "mcc": "5411",
    "avg_amount": 60.25
  },
  "terminal": {
    "is_online": false,
    "card_present": true,
    "km_from_home": 29.2331036248
  },
  "last_transaction": null
}

### Score 0.2
POST {{baseUrl}}/fraud-score
Content-Type: application/json

{
  "id": "tx-2549846621",
  "transaction": {
    "amount": 2438.21,
    "installments": 4,
    "requested_at": "2026-03-12T07:45:51Z"
  },
  "customer": {
    "avg_amount": 278.8,
    "tx_count_24h": 11,
    "known_merchants": ["MERC-012", "MERC-015", "MERC-010", "MERC-018"]
  },
  "merchant": {
    "id": "MERC-039",
    "mcc": "5311",
    "avg_amount": 185.09
  },
  "terminal": {
    "is_online": true,
    "card_present": false,
    "km_from_home": 206.517733351
  },
  "last_transaction": null
}

### Score 0.4
POST {{baseUrl}}/fraud-score
Content-Type: application/json

{
  "id": "tx-2174907811",
  "transaction": {
    "amount": 1265.15,
    "installments": 6,
    "requested_at": "2026-03-25T19:00:34Z"
  },
  "customer": {
    "avg_amount": 349.94,
    "tx_count_24h": 5,
    "known_merchants": ["MERC-014", "MERC-001", "MERC-008", "MERC-003"]
  },
  "merchant": {
    "id": "MERC-031",
    "mcc": "7802",
    "avg_amount": 107.11
  },
  "terminal": {
    "is_online": true,
    "card_present": false,
    "km_from_home": 136.5069519371
  },
  "last_transaction": {
    "timestamp": "2026-03-25T17:09:34Z",
    "km_from_current": 131.6216524485
  }
}

### Score 0.6
POST {{baseUrl}}/fraud-score
Content-Type: application/json

{
  "id": "tx-2642173001",
  "transaction": {
    "amount": 1990.34,
    "installments": 5,
    "requested_at": "2026-03-25T06:57:14Z"
  },
  "customer": {
    "avg_amount": 129.76,
    "tx_count_24h": 11,
    "known_merchants": ["MERC-014", "MERC-007", "MERC-007", "MERC-006", "MERC-001"]
  },
  "merchant": {
    "id": "MERC-048",
    "mcc": "7801",
    "avg_amount": 179.66
  },
  "terminal": {
    "is_online": true,
    "card_present": false,
    "km_from_home": 218.7310019761
  },
  "last_transaction": {
    "timestamp": "2026-03-25T05:57:14Z",
    "km_from_current": 144.4672744732
  }
}

### Score 0.8
POST {{baseUrl}}/fraud-score
Content-Type: application/json

{
  "id": "tx-4112059057",
  "transaction": {
    "amount": 2690.86,
    "installments": 7,
    "requested_at": "2026-03-13T13:13:03Z"
  },
  "customer": {
    "avg_amount": 321.52,
    "tx_count_24h": 10,
    "known_merchants": ["MERC-001", "MERC-013", "MERC-010"]
  },
  "merchant": {
    "id": "MERC-041",
    "mcc": "5999",
    "avg_amount": 54.8
  },
  "terminal": {
    "is_online": true,
    "card_present": false,
    "km_from_home": 131.2017162031
  },
  "last_transaction": {
    "timestamp": "2026-03-13T11:15:03Z",
    "km_from_current": 65.4420049781
  }
}

### Score 1.0
POST {{baseUrl}}/fraud-score
Content-Type: application/json

{
  "id": "tx-1788243118",
  "transaction": {
    "amount": 4368.82,
    "installments": 8,
    "requested_at": "2026-03-17T02:04:06Z"
  },
  "customer": {
    "avg_amount": 68.88,
    "tx_count_24h": 18,
    "known_merchants": ["MERC-004", "MERC-004", "MERC-015", "MERC-017", "MERC-007"]
  },
  "merchant": {
    "id": "MERC-062",
    "mcc": "7801",
    "avg_amount": 25.55
  },
  "terminal": {
    "is_online": true,
    "card_present": false,
    "km_from_home": 881.6139684714
  },
  "last_transaction": {
    "timestamp": "2026-03-17T01:58:06Z",
    "km_from_current": 660.9200962961
  }
}
